name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android NDK
        run: |
          sdkmanager --install "ndk;21.4.7075529"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ant libglu1-mesa

      - name: Build native code
        working-directory: ./proj.android
        run: |
          $ANDROID_NDK_HOME/ndk-build -C jni

      - name: Update project configuration
        working-directory: ./proj.android
        run: |
          android update project -p . -t android-29

      - name: Build debug APK
        working-directory: ./proj.android
        run: |
          ant debug
